region                 = "us-east-1"
vpc_name               = "eks-vpc"
vpc_cidr               = "10.0.0.0/16"
azs                    = ["us-east-1a", "us-east-1b"]
public_subnets         = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets        = ["10.0.3.0/24", "10.0.4.0/24"]
intra_subnets          = ["10.0.5.0/24", "10.0.6.0/24"]
enable_nat_gateway     = true
single_nat_gateway     = true
enable_dns_hostnames   = true
enable_dns_support     = true
eks_cluster_name       = "terraform-eks-cluster"
kubernetes_version     = "1.33"
node_instance_type     = "t3.medium"
node_ami_type          = "AL2023_x86_64_STANDARD"
node_capacity_type     = "SPOT"
node_min_size          = 2
node_max_size          = 3
node_desired_size      = 2
endpoint_public_access = true
